### ISSUE TITLE
有个用法有疑问

### ISSUE THREAD

**Issue by guangqiang-liu** [beforeold/GSForm#1]
作者，你好，你的这个表单组件有个地方不是很明白，希望讲解下，你的简书地址找不到了，只能在这联系了

**Comment by beforeold** [comment]
Glad that you submitted an issue to discuss this project. You can find my blog in GitHub directory [Tech_blogs](https://github.com/beforeold/techblogs/blob/master/iOS/%5BiOS%5D-%5BOC%5D--%E8%BD%BB%E9%87%8F%E7%BA%A7%E7%9A%84%E8%A1%A8%E5%8D%95%E6%A1%86%E6%9E%B6-GSForm%EF%BC%88%E9%99%84demo%EF%BC%89.md)
